### ISSUE TITLE
Retrieve specific userinfo field

### ISSUE THREAD

**Issue by Razish** [Razish/japp#80]
to avoid the overhead of generating a table of every key/value pair

**Comment by EpicLoyd** [comment]
Fixed in be86447a2b08668061ed58965c16c71bc5796797

**Comment by ensiform** [comment]
That isn't really solving it.  You are still getting the whole string.

**Comment by EpicLoyd** [comment]
lol but there no way to get 'not a whole string' : d

**Comment by Razish** [comment]
Yeah, this fix is good enough. The issue was not avoiding retrieving the infostring from the engine, but avoiding creating/passing the whole table to Lua

**Comment by ensiform** [comment]
Well there is if you cache it and tokenize out the result upon initial retrieval from engine.
